<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNH43NPc\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNH43NPc/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNH43NPc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNH43NPc\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerNH43NPc\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'NH43NPc',
    'container.build_id' => 'ea648971',
    'container.build_time' => 1765283874,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNH43NPc');
