<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ5zb8Lm\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ5zb8Lm/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQ5zb8Lm.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQ5zb8Lm\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQ5zb8Lm\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Q5zb8Lm',
    'container.build_id' => 'f0d80429',
    'container.build_time' => 1765870107,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ5zb8Lm');
