<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\DefaultController::index'], [], [['text', '/']], [], []],
    'getUsuarios' => [[], ['_controller' => 'App\\Controller\\UsuarioController::getUsuarios'], [], [['text', '/usuarios']], [], []],
    'registro' => [[], ['_controller' => 'App\\Controller\\UsuarioController::createUsuario'], [], [['text', '/usuario/registro']], [], []],
    'updateUsuario' => [['id'], ['_controller' => 'App\\Controller\\UsuarioController::updateUsuario'], [], [['text', '/update'], ['variable', '/', '[^/]++', 'id'], ['text', '/usuario']], [], []],
    'updateConfig' => [['idUsuario'], ['_controller' => 'App\\Controller\\UsuarioController::updateConfig'], [], [['text', '/config/update'], ['variable', '/', '[^/]++', 'idUsuario'], ['text', '/usuario']], [], []],
    'getVehiculos' => [[], ['_controller' => 'App\\Controller\\VehiculosController::getVehiculos'], [], [['text', '/vehiculos']], [], []],
    'getVehiculosByUser' => [['userId'], ['_controller' => 'App\\Controller\\VehiculosController::getVehiculosByUser'], [], [['text', '/vehiculos'], ['variable', '/', '[^/]++', 'userId'], ['text', '/usuario']], [], []],
    'createVehiculo' => [[], ['_controller' => 'App\\Controller\\VehiculosController::createVehiculo'], [], [['text', '/vehiculo/create']], [], []],
    'deleteVehiculo' => [['id'], ['_controller' => 'App\\Controller\\VehiculosController::deleteVehiculos'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/vehiculo']], [], []],
    'updateVehiculo' => [['id'], ['_controller' => 'App\\Controller\\VehiculosController::updateVehiculos'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/vehiculo']], [], []],
    'createDispositivo' => [[], ['_controller' => 'App\\Controller\\DispositivosController::createDispositivo'], [], [['text', '/dispositivo/create']], [], []],
    'updateDispositivo' => [['id'], ['_controller' => 'App\\Controller\\DispositivosController::updateDispositivo'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/dispositivo']], [], []],
];
